[package]
name = "dummy"
version = "0.1.0"
authors = ["Agustin Chiappe Berrini <jnieve@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.0"
lachesis-rs = { path = "../lachesis-rs" }
log = "0.4"
rand = "0.6.0"
ring = "0.13.4"
untrusted = "0.6.2"
failure = "0.1.5"
